config/routes.rb
Traininglite::Application.routes.draw do

	
	
	get "log_in" => "sessions#new", :as => "log_in"  
	get "log_out" => "sessions#destroy", :as => "log_out"
	get "sign_up" => "users#new", :as => "sign_up"
	
	resources :users, :products, :categories, :sessions
	
	namespace :admin do
    resources :categories
  end
	
	root :to => 'categories#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  # attr_accessible :title, :body
	has_many :comments,  :dependent => :destroy # plural
	belongs_to :user
	
	validates :title, :presence => true
	validates :body, :presence => true
	validates :user_id, :presence => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  # attr_accessible :title, :body
	has_many :products,  :dependent => :destroy # plural
	#belongs_to :parent
	#has_many :children, :foreign_key => :parent_id
	
	validates :name, :presence => true
	#validates :parent_id, :presence => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :title, :body
	belongs_to :article
	
	validates :comment, :presence => true
	validates :article_id, :presence => true
	validates :user_id, :presence => true
end

app/models/product.rb
class Product < ActiveRecord::Base
  # attr_accessible :title, :body
	belongs_to :user
	belongs_to :category

	
	validates :name, :presence => true
	validates :description, :presence => true
	validates :price, :presence => true
	#validates :weight, :presence => true
	validates :user_id, :presence => true
	validates :category_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
	has_many :products,  :dependent => :destroy # plural
	has_many :articles,  :dependent => :destroy # plural
	
	validates :email, :presence => true,
	                  :length => {:minimum => 3, :maximum => 254},
                    :uniqueness => true,
                    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
	#validates :password_hash, :presence => true
	#validates :password_salt, :presence => true
	validates :name, :presence => true,
	                 :length => {:minimum => 1, :maximum => 254},
                   :format => {:with => /[a-zA-Z\s]+$/}
	validates :address, :presence => true
	#validates :phone_number, :presence => true
	#validates :birthday, :presence => true
	validates :gender, :presence => true
	#validates :facebook, :presence => true
	#validates :blog, :presence => true
	
	validates :password, :presence => {:on => :create},
                     :confirmation => true
	
	def is_admin?
		self.email == "admin@admin.com"
	end
	
	#LOGIN
	attr_accessor :password, :password_confirmation
	before_save :encrypt_password
	
	def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
	def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
	end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  protect_from_forgery

  def require_admin_login
     if current_user.nil? || !current_user.is_admin?
       flash[:error] = "Only admins are permitted"
       redirect_to log_in_path
    else
       return current_user
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  protect_from_forgery
	before_filter :require_admin_login
	
	def new
	  @category = Category.new
  end
	
	def create
	  #raise params[:product].inspect
	  @category = Category.new(params[:category])
		if @category.save
		  flash[:notice] = 'Your Category was succesfully created'
			redirect_to root_path
		else
		  flash[:error] = 'Your Category was failed to create'
			render :action => "new"
		end
	end
	
	def edit
	  @category = Category.find_by_id(params[:id])
  end
	
	def update
	  @category = Category.find_by_id(params[:id])
		if @category.update_attributes(params[:category])
		  flash[:notice] = 'Category was successfully updated'
			redirect_to edit_admin_category_path
		else
		  flash[:error] = 'Category was failed to update'
			redirect_to edit_admin_category_path
		end
	end
	
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to root_path#:controller => :categories, :action => :index
		flash[:notice] = 'Category was successfully deleted.'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  #before_filter :require_login, :only => [:index]
	#before_filter :require_admin_login, :only => [:new, :create, :edit, :update, :delete]
	 
  def index
		@categories = Category.all
		@parent = Category.find_by_id(params[:id])
  end
	
	#def destroy
  #  @category = Category.find(params[:id])
  #  @category.destroy
  #  redirect_to :controller => :categories, :action => :index
	#	flash[:notice] = 'category was successfully deleted.'
  #end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
	  @products = Product.all
  end
	
	def show
		@product = Product.find_by_id(params[:id])
  end

  def edit
		@product = Product.find_by_id(params[:id])
  end
	
	def update
	  @product = Product.find_by_id(params[:id])
		if @product.update_attributes(params[:product])
		  flash[:notice] = 'Your product was succesfully updated'
			render :action => "edit"
		else
		  flash[:error] = 'Your product was failed to update'
			render :action => "edit"
		end
	end

  def new
	  @product = Product.new
  end

  def create
	  @product = Product.new(params[:product])
		if @product.save
		  flash[:notice] = 'Your product was succesfully created'
			redirect_to root_path
		else
		  flash[:error] = 'Your product was failed to create'
			render :action => "new"
		end
	end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password" 
      render "new"
    end
  end
	
	def destroy
    session[:user_id] = nil
    redirect_to root_path, :notice => "Logged out!"
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :already_login, :only => [:new, :create, :edit, :update, :delete]
  def new 
    @user = User.new 
  end 

  def create 
    @user = User.new(params[:user]) 
    if @user.save 
      redirect_to root_url, :notice => "Signed up!" 
    else 
      render "new" 
    end 
  end 
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def welcome_text
    str = "" # if the user has logged in, show the welcome text.
    if current_user
      str = "Welcome, #{current_user.name} | "
      str += link_to "Logout", log_out_path
    else
      str = "Welcome, Guest | "
		  str += "#{link_to "Login", log_in_path} | "
      str += link_to "Signup", sign_up_path
    end
  end 
	
	def category_option
	  str = "" # if the user has logged in, show the welcome text.
    if is_admin
      str = link_to "Edit ", edit_admin_category_path
			str += link_to "Delete", admin_category_path, :method => :delete
    else
      str = ""
    end
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/edit.html.erb
<section class="category edit admin">
		<% @parent_category = Category.where("parent_id IS null").map{|c| [c.name, c.id]} %>
	  <%= form_for @category, :method => :put, :url => :admin_category do |f| %>
	    <div class="row"><label>Category Name :</label> <%= f.text_field :name %></div>
		  <div class="row"><label>Parent Category :</label> <%= f.select :parent_id, @parent_category, { :include_blank => true } %></div>
		  <%#= hidden_field :product, :user_id, :value => current_user.id %>
		  <div class="row"><%=f.submit :update%></div>
	  <% end %>
	<div class="clear"></div>
	<span class="flash notice"><%= flash[:notice] %></span>
	<span class="flash error"><%= flash[:error] %></span>
</section>

app/views/admin/categories/new.html.erb
<section class="category add admin">
  <!-- <%# if @category.errors.any? %> 
    <div class="error_messages"> 
      <h2>Form is invalid</h2> 
      <ul> 
        <%# for message in @category.errors.full_messages %> 
          <li><%#= message %></li> 
        <%# end %> 
      </ul> 
    </div> 
  <%# end %> --> 
  <% @parent_category = Category.where("parent_id IS null").map{|c| [c.name, c.id]} %>
	<%= form_for @category, :url => :admin_categories do |f| %>
	  <div class="row"><label>Category Name :</label> <%= f.text_field :name %></div>
		<div class="row"><label>Parent Category :</label> <%= f.select :parent_id, @parent_category, { :include_blank => true } %></div>
		<%#= hidden_field :product, :user_id, :value => current_user.id %>
		<div class="row"><%=f.submit :new%></div>
	<% end %>
	<div class="clear"></div>
	<span class="flash notice"><%= flash[:notice] %></span>
	<span class="flash error"><%= flash[:error] %></span>
</section>

app/views/categories/index.html.erb
<section class="category index">
  <h2>List Categories Page</h2>
	<span><%= link_to "Add New Category", new_admin_category_path %></span>
  <table class="list category">
		<tr>
		  <th>Name</th>
			<th>Parent Category</th>
			<th></th>
		</tr>
    <% @categories.each do |c| %>
    <tr>
	    <td><%= c.name %></td>
			<td>
				<%#= c.parent.name if c.parent.present? %>
				<% if c.parent_id.nil? %>
				  <%= '-' %>
				<% else %>
				  <%= Category.find_by_id(c.parent_id).name %>
				<% end %>
			</td>
			<td>
			  <%= link_to "Show", category_path(c.id) %>
				<%#= raw(category_option) %>
				<%#= link_to "Edit", edit_admin_category_path(c.id) %>
				<%#= link_to "Delete", admin_category_path(c.id), :confirm => 'Are you sure want to delete this category?', :method => :delete %>
			</td>
	  </tr>
  <% end %>
</table>
<div class="clear"></div>
<span class="flash notice"><%= flash[:notice] %></span>
<span class="flash error"><%= flash[:error] %></span>
</section> <!-- END OF CATEGORIES INDEX -->

app/views/categories/show.html.erb
<section class="category show">
	<h2><%= @category.name %></h2>
	<span>Category Name : <%= @category.name %></span>
	<span>Category Name : <%= @category.name %></span>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Online Store - Training</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<section id="wrapper">
		<section class="wrapper">
      <header id="main">
		    <h1>Welcome to My Store</h1>
		    <nav>
			    <ul>
			  	  <li><%= link_to "Home", root_path %></li>
			  	  <li><%= link_to "Products", products_path %></li>
			   	  <li><a href="javascript.void(0)">Articles</a></li>
				    <li><a href="javascript.void(0)">Categories</a></li>
			    </ul>
		    </nav>
				<section>
				  <%= raw(welcome_text) %>
				</section>
      </header>
	
      <section id="main">
        <%= yield %>
      </section><!-- END OF MAIN -->
			<div class="push"></div>
	  </section><!-- END OF CLASS WRAPPER -->
	  <footer id="main">
	    <section>
			  &copy; Ruby on Rails Training - Walden Global Services 2012
		  </section>
	  </footer>
		<div class="clear"></div>
	</section> <!-- END OF ID WRAPPER -->
</body>
</html>

app/views/products/edit.html.erb
<section class="product edit">
	<%= form_for @product do |f| %>
	  <div class="row"><label>Product Name :</label> <%= f.text_field :name %></div>
		<div class="row"><label>Product Price :</label> <%= f.text_field :price %></div>
		<div class="row"><label>Product Weight :</label> <%= f.text_field :weight %></div>
		<div class="row"><label>Product Description :</label> <%= f.text_area :description %></div>
		<div class="row"><%=f.submit :update%></div>
	<% end %>
	<div class="clear"></div>
	<span class="flash notice"><%= flash[:notice] %></span>
	<span class="flash error"><%= flash[:error] %></span>
</section>

app/views/products/index.html.erb
<section class="product index">
  <h2>Products Page</h2>
  <ul class="list products">
    <% @products.each do |p| %>
    <li>
	    <h4><%= p.name %></h4>
	    <p><%= p.description[0,30] + "..." %></p>
			<div>
				<%= link_to "See More", product_path(p.id) %>
				<%= link_to "Edit", edit_product_path(p.id) %>
			</div>
			<span>Category: <%= p.category.name %></span>
	  </li>
  <% end %>
</ul>
</section> <!-- END OF PRODUCTS INDEX -->

app/views/products/new.html.erb
<section class="product add">
	<%= form_for @product do |f| %>
	  <div class="row"><label>Product Name :</label> <%= f.text_field :name %></div>
		<div class="row"><label>Product Price :</label> <%= f.text_field :price %></div>
		<div class="row"><label>Product Weight :</label> <%= f.text_field :weight %></div>
		<div class="row"><label>Product Description :</label> <%= f.text_area :description %></div>
		<div class="row">
		  <label>Product Category :</label> 
			<%#= select_tag(:category_id, '<option value="1">Lisbon</option>') %>
		</div>
		<%#= hidden_field :product, :user_id, :value => current_user.id %>
		<div class="row"><%=f.submit :new%></div>
	<% end %>
	<div class="clear"></div>
	<span class="flash notice"><%= flash[:notice] %></span>
	<span class="flash error"><%= flash[:error] %></span>
</section>

app/views/products/show.html.erb
<section class="product show">
	<h2><%= @product.name %></h2>
	<span>Price : <%= @product.price %></span>
	<span>Weight : <%= @product.weight %></span>
	<p><%= @product.description %></p>
</section>

app/views/users/new.html.erb
<section class="user add">
  <%= form_for @user do |f| %> 
    <% if @user.errors.any? %> 
      <div class="error_messages"> 
        <h2>Form is invalid</h2> 
        <ul> 
          <% for message in @user.errors.full_messages %> 
            <li><%= message %></li> 
          <% end %> 
        </ul> 
      </div> 
    <% end %> 
    <div class="row"> 
      <%= f.label :email %>
      <%= f.text_field :email %> 
    </div> 
    <div class="row"> 
      <%= f.label :password %>
      <%= f.password_field :password %> 
    </div> 
    <div class="row"> 
      <%= f.label :password_confirmation %> 
      <%= f.password_field :password_confirmation %> 
    </div>
		<div class="row"> 
      <%= f.label :name %> 
      <%= f.text_field :name %> 
    </div>
		<div class="row"> 
      <%= f.label :address %> 
      <%= f.text_field :address %> 
    </div>
		<div class="row"> 
      <%= f.label :gender %> 
      <%= f.text_field :gender %> 
    </div>
		<div class="row"> 
      <%= f.label :facebook %> 
      <%= f.text_field :facebook %> 
    </div>
		<div class="row"> 
      <%= f.label :blog %> 
      <%= f.text_field :blog %> 
    </div>
    <div class="row button"><%= f.submit :new%></div> 
	<% end %> 
</section>